# Generated by Django 4.2.1 on 2023-06-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_timezone_timezone_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezone',
            name='timezone_str',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
