# Generated by Django 4.2.1 on 2023-06-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_buissnesshour_day_of_week_buissnesshour_store_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buissnesshour',
            name='store_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='storestatus',
            name='store_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='store_id',
            field=models.BigIntegerField(),
        ),
    ]
