# Generated by Django 4.2.1 on 2023-06-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_buissnesshour_store_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='timezone_str',
            field=models.CharField(max_length=50),
        ),
    ]
