# Generated by Django 4.2.1 on 2023-06-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_timezone_timezone_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buissnesshour',
            name='end_time_local',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='buissnesshour',
            name='start_time_local',
            field=models.TimeField(),
        ),
    ]
